server:
  port: 8000
spring:
  datasource:
    driverClassName: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5433/elite}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true